### ISSUE TITLE
Multisports Fitness Trend  curves KO since today's update

### ISSUE THREAD

**Issue by xanadonf** [thomaschampagne/stravistix#350]
This morning I set Swimming my Functional Threshold Pace -> empty graphics on MFT page if I enable Swim Stress Score.
I synced again, same problem.
If I don't enable SSS, it's ok.

![image](https://cloud.githubusercontent.com/assets/142837/23754029/d8349986-04db-11e7-9947-e685ef15ec8e.png)

Chrome up to date. Plugin up to date.

Console errors below:
`FitnessDataService.js:205 Fetch fitnessData from fitnessDataService.getFitnessData
FitnessDataService.js:64 Fetch fitnessObjectsWithDaysOff from fitnessDataService.getFitnessObjectsWithDaysOff
FitnessDataService.js:179 First preview day is Fri Mar 10 2017 00:00:00 GMT+0100 (CET)
FitnessDataService.js:210 Generating FitnessData from storage took 931 ms.
fitnessTrendGraph.js:17 FitnessTrendGraph: message fitnessDataLoaded received
fitnessTrendGraph.js:259 Configure graph options
fitnessTrendTable.js:8 FitnessTrendTable: message fitnessDataLoaded received
fitnessTrendGraph.js:531 Generating Fitness Graph took 588 ms.
FitnessDataService.js:205 Fetch fitnessData from fitnessDataService.getFitnessData
FitnessDataService.js:64 Fetch fitnessObjectsWithDaysOff from fitnessDataService.getFitnessObjectsWithDaysOff
FitnessDataService.js:179 First preview day is Fri Mar 10 2017 00:00:00 GMT+0100 (CET)
FitnessDataService.js:210 Generating FitnessData from storage took 783 ms.
fitnessTrendGraph.js:17 FitnessTrendGraph: message fitnessDataLoaded received
fitnessTrendGraph.js:259 Configure graph options
fitnessTrendTable.js:8 FitnessTrendTable: message fitnessDataLoaded received
fitnessTrendGraph.js:531 Generating Fitness Graph took 471 ms.
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16322
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9321
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16389
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9406
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16322
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9321
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16389
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9406
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16322
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9321
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16389
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9406
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16322
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9321
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16389
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9406
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16322
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9321
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16389
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9406
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16322
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9321
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
fitnessTrendGraph.js:245 Uncaught TypeError: Cannot read property 'toUpperCase' of null
    at Scope.FitnessTrendGraph.$scope.makeTooltip (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:245:151)
    at contentGenerator (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/directives/fitnessTrend/fitnessTrendGraph.js:308:43)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5990
    at Object.a.dom.write (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:2071)
    at c (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:5963)
    at Object.set (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:10311)
    at Function.a._calls.a._calls.(anonymous function).a.(anonymous function) [as hidden] (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:3:15595)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:16389
    at event (chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/d3/d3.js:504:42)
    at chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/node_modules/nvd3/build/nv.d3.min.js:6:9406
FitnessTrendGraph.$scope.makeTooltip @ fitnessTrendGraph.js:245
contentGenerator @ fitnessTrendGraph.js:308
(anonymous) @ nv.d3.min.js:3
a.dom.write @ nv.d3.min.js:3
c @ nv.d3.min.js:3
set @ nv.d3.min.js:3
a._calls.a._calls.(anonymous function).a.(anonymous function) @ nv.d3.min.js:3
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
(anonymous) @ nv.d3.min.js:6
event @ d3.js:504
i @ nv.d3.min.js:9
(anonymous) @ nv.d3.min.js:9
(anonymous) @ d3.js:1120
`

**Comment by thomaschampagne** [comment]
@xanadonf Thx for report

Could you provide me a backup of your history? Checking this tonight ;)

Thanks

**Comment by thomaschampagne** [comment]
Click the "clock" icon in top right corner, then "backup history" and send the file to th.champagne[at]gmail.com or upload here. Ty

**Comment by xanadonf** [comment]
Yep, all my life should already be in in your mailbox ;o)

**Comment by thomaschampagne** [comment]
@xanadonf Fixed in 5.6.1 ;) Available this evening from chrome store ;)

Tom

**Comment by xanadonf** [comment]
I patched and this seems ok, thx Thomas ;o)
